Config = {}

Config.armasPermitidas = { --- Aquí se definen las armas permitidas
    "weapon_dagger",
    "weapon_bat",
    "weapon_bottle",
    "weapon_crowbar",
    "weapon_unarmed",
    "weapon_flashlight",
    "weapon_golfclub",
    "weapon_hammer",
    "weapon_hatchet",
    "weapon_knuckle",
    "weapon_knife",
    "weapon_machete",
    "weapon_switchblade",
    "weapon_nightstick",
    "weapon_wrench",
    "weapon_battleaxe",
    "weapon_poolcue",
    "weapon_stone_hatchet",
    "weapon_hazardcan",
    "weapon_petrolcan",
    "weapon_fireextinguisher",
    "gadget_parachute",
    "weapon_fertilizercan",
    "weapon_ball", 
    "weapon_snowball",
    "weapon_molotov",
    "weapon_proxmine",   
    "weapon_stickybomb",
    "weapon_pipebomb",
    "weapon_grenade",
    "weapon_bzgas",
}